#name: API call
#on:
#  schedule:
#    - cron: '50 1/2 * * *' #call every two hours, starting at 1:45
#  workflow_dispatch:
#jobs:
#  Explore-GitHub-Actions:
#    runs-on: ubuntu-latest
#    steps:
#      - name: checkout repo content
#        uses: actions/checkout@v2 # checkout the repository content to github runner.
#      - name: setup python
#        uses: actions/setup-python@v2
#        with:
#          python-version: 3.8 #install the python needed
#      - name: add library
#        run: |
#          pip install requests
#          pip install pytz
#          pip install python-dateutil
#      - name: execute py script # run the run.py to get the latest data
#        run: |
#          python updateJson.py
#     - name: Commit and push changes
#        run: |
#          git config --global user.name "Kiparte"
#          git config --global user.email "Valorx43@gmail.com"
#          git add -A
#          git commit -m "periodic commit"
          git push
